name: build dcker image and push to registry
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Build the Docker image
        uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file docker/Dockerfile --tag fc-bank:latest
      - name: Prepare Push the Docker Image
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
      - name: Push the Docker Image
        run: docker image push rafaeldalarosa/fc-bank:latest
        
        

