name: build docker image and push to registry
on:
  push:
    branches: [ "main" ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Build the Docker image
        uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t fc-bank:latest -f docker/Dockerfile .
      - name: Prepare Push the Docker Image
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
      - name: Log in Docker Hub
        run: docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASS }}
      - name: Push the Docker Image
        run: docker image push ${{ secrets.REGISTRY_USER }}/fc-bank:latest
        
        

